### PR TITLE
Add buildroot support for redpitaya12: Signal Lab

### PR DESCRIPTION
**Pull request by sdenis6**

### CODE REVIEW

**Comment by trabucayre** [comment]
Hi and thanks. Globally looks good for me but I have some small complains:

- you modify `zynq-red_pitaya.dts` for linux. There are a reason?
- 0010-add_red_pitaya12_dts.patch ->` u-boot-2019.07/arch/arm/dts/Makefile` : wrong indent
- 0001-redpitaya12-add_devicetree.patch must be moved in the upper directory
- redpitaya12_defconfig:
   - you use `zynq-red_pitaya.dts` instead of `zynq-red_pitaya12.dts`
   - `BR2_LINUX_KERNEL_PATCH` is not required. Buildroot will use `BR2_GLOBAL_PATCH_DIR`

**Comment by sdenis6** [comment]
Hi, thanks for your reply. 

I modified the zynq-red_pitaya.dts for linux to adapt it to the new redpitaya SignalLab board. On this board:

- the address of one gpio system led changes,
- the VCXO that manage the clock must be included in the device tree. 

Because of this I initially wanted to make a patch for linux to make a second device tree called "zynq-red_pitaya12.dts", placed in the xxx/redpitaya/board/redpitaya/patches/linux/xilinx-v2019.1 directory (and indeed indicate it in the file redpitaya12_defconfig), but the name of the device tree also had to be mentioned in the redpitaya/board/redpitaya/genimage.cfg file for the post-image script. Then I saw two options:

1. Create a second file genimage12.cfg calling the good device tree name: "zynq-red_pitaya12.dts", and indicate in the redpitaya12_defconfig to use this file.
2. Create a sub-directory in redpitaya/board/redpitaya/patches/linux/xilinx-v2019.1 where I put an additional patch to modify the existing zynq-red_pitaya.dts file. Then add the variable BR2_LINUX_KERNEL_PATCH in the file redpitaya12_defconfig so that the additional linux patch (in the sub-directory) is applied for this board only, and not when other defconfig are used. 

With my understanding of all this I could not find a third option that would be more satisfying. Is there another way ? 

For the wrong indent: I think it is corrected !

**Comment by trabucayre** [comment]
indent it's ok for me.
for dts an idea is to use something like this [freescale](https://git.buildroot.net/buildroot/tree/board/freescale/common/imx/post-image.sh): a genimage template where the dts name is replaces by correct name.

**Comment by sdenis6** [comment]
Ok ! I think I got it. 

So I just:
1. made the script redpitaya/board/redpitaya/post-image.sh that make a symlink of BR2_LINUX_KERNEL_INTREE_DTS_NAME (whatever it is) to zynq-red_pitaya.dtb
2. turned BR2_ROOTFS_POST_IMAGE_SCRIPT="support/scripts/genimage.sh into BR2_ROOTFS_POST_IMAGE_SCRIPT="$(BR2_EXTERNAL_REDPITAYA_PATH)/board/redpitaya/post-image.sh"
3. made all the modifications for the linux device tree patch. 

Is it what you expected ?

**Comment by trabucayre** [comment]
It's near my idea :) 
Okay for the post-image.sh
but with:
```
DTB="$(sed -n 's/^BR2_LINUX_KERNEL_INTREE_DTS_NAME="\([\/a-z0-9_ \-]*\)"$/\1/p' ${BR2_CONFIG})"
BOARD_PATH="$(dirname $0)"

GENIMAGE_CFG="$(mktemp --suffix genimage.cfg)"
GENIMAGE_TMP="${BUILD_DIR}/genimage.tmp"

sed -e "s/%DTBFILE%/${DTB}/" \
    ${BOARD_PATH}/genimage-template.cfg \
    > ${GENIMAGE_CFG}

rm -rf "${GENIMAGE_TMP}"

genimage \
    --rootpath "${TARGET_DIR}" \
    --tmppath "${GENIMAGE_TMP}" \
    --inputpath "${BINARIES_DIR}" \
    --outputpath "${BINARIES_DIR}" \
    --config "${GENIMAGE_CFG}"

rm -f ${GENIMAGE_CFG}
```
the genimage.cfg must be renamed by genimage-template.cfg
with the line
```
"zImage",
"zynq-red_pitaya.dtb"
```
replaced by
```
"zImage",
"%DTBFILE%.dtb"
```

**Comment by sdenis6** [comment]
Ok, better :D 

Should we find a way to rename automatically the devicetree_image value in uEnv.txt ?

And the redpitaya_xenomai_defconfig doesn't have the variable BR2_LINUX_KERNEL_INTREE_DTS_NAME, but BR2_LINUX_KERNEL_CUSTOM_DTS_PATH instead. The post-image.sh may need to be adapted, or I can make the linux dts patch for the xenomai config.

**Comment by sdenis6** [comment]
Like this ?

**Comment by trabucayre** [comment]
Last thing: update the README to add instructions for this board.
Thank

**Comment by sdenis6** [comment]
Is it ok ? I did not add any note for the devicetree_image variable in uEnv.txt.

**Comment by trabucayre** [comment]
Applied thanks!

**Pull request merged**
